import { StyleSheet } from "react-native";

export const profileStyles = StyleSheet.create({
screen: {
flex: 1,
backgroundColor: "#0b0b0f",
},
content: {
padding: 20,
paddingBottom: 140,
gap: 16,
},
center: {
flex: 1,
backgroundColor: "#0b0b0f",
alignItems: "center",
justifyContent: "center",
},
centerText: {
color: "#c3c7d4",
marginTop: 10,
},
card: {
backgroundColor: "#15161c",
borderWidth: 1,
borderColor: "#24252d",
borderRadius: 18,
padding: 18,
gap: 8,
},
name: {
color: "#ffffff",
fontSize: 22,
fontWeight: "700",
},
email: {
color: "#b5b5c0",
fontSize: 14,
},
statsRow: {
flexDirection: "row",
gap: 10,
marginTop: 6,
},
statBox: {
flex: 1,
backgroundColor: "#101218",
borderWidth: 1,
borderColor: "#20222c",
borderRadius: 14,
padding: 12,
},
statValue: {
color: "#ffffff",
fontSize: 18,
fontWeight: "700",
},
statLabel: {
color: "#8f90a0",
marginTop: 2,
fontSize: 12,
},
section: {
backgroundColor: "#15161c",
borderWidth: 1,
borderColor: "#24252d",
borderRadius: 18,
padding: 16,
gap: 10,
},
sectionDanger: {
backgroundColor: "#1c1313",
borderWidth: 1,
borderColor: "#4a2020",
borderRadius: 18,
padding: 16,
gap: 10,
},
sectionTitle: {
color: "#ffffff",
fontSize: 18,
fontWeight: "700",
},
muted: {
color: "#8f90a0",
fontSize: 14,
},
songRow: {
flexDirection: "row",
alignItems: "center",
gap: 10,
backgroundColor: "#101218",
borderWidth: 1,
borderColor: "#20222c",
borderRadius: 12,
padding: 12,
},
songTitle: {
color: "#ffffff",
fontWeight: "700",
},
songArtist: {
color: "#b5b5c0",
fontSize: 13,
marginTop: 2,
},
deleteSongBtn: {
paddingHorizontal: 10,
paddingVertical: 8,
borderRadius: 999,
borderWidth: 1,
borderColor: "#d66262",
},
deleteSongText: {
color: "#ff8f8f",
fontWeight: "700",
fontSize: 12,
},
label: {
color: "#d4d7e2",
fontSize: 13,
marginTop: 4,
},
input: {
backgroundColor: "#101218",
borderWidth: 1,
borderColor: "#2a2d38",
borderRadius: 12,
color: "#ffffff",
paddingHorizontal: 12,
paddingVertical: 10,
},
primaryBtn: {
marginTop: 8,
backgroundColor: "#2a6cff",
borderRadius: 999,
alignItems: "center",
paddingVertical: 12,
},
primaryText: {
color: "#ffffff",
fontWeight: "700",
},
dangerBtn: {
marginTop: 8,
backgroundColor: "#2b1515",
borderWidth: 1,
borderColor: "#b14b4b",
borderRadius: 999,
alignItems: "center",
paddingVertical: 12,
},
dangerText: {
color: "#ff9c9c",
fontWeight: "700",
},
disabledBtn: {
opacity: 0.6,
},
page: {
  padding: 20,
  paddingBottom: 140,
},
layout: {
  flexDirection: "row",
  gap: 20,
  alignItems: "flex-start",
},
layoutMobile: {
  flexDirection: "column",
},
fullWidth: {
  width: "100%",
},
leftSidebar: {
  width: 250,
  backgroundColor: "#15161c",
  borderColor: "#24252d",
  borderWidth: 1,
  borderRadius: 14,
  padding: 14,
  gap: 8,
},
centerPanel: {
  flex: 1,
  minWidth: 0,
},
rightSidebar: {
  width: 250,
  backgroundColor: "#15161c",
  borderColor: "#24252d",
  borderWidth: 1,
  borderRadius: 14,
  padding: 18,
  alignItems: "center",
},
navItem: {
  borderRadius: 10,
  paddingVertical: 12,
  paddingHorizontal: 12,
},
navItemActive: {
  backgroundColor: "#1f2028",
},
navText: {
  color: "#c4c7d2",
  fontSize: 22,
},
navTextActive: {
  color: "#ffb547",
  fontWeight: "700",
},
sidebarDivider: {
  marginTop: 12,
  borderTopWidth: 1,
  borderTopColor: "#2a2d38",
  paddingTop: 12,
},
sidebarGhostBtn: {
  borderWidth: 1,
  borderColor: "#d66262",
  borderRadius: 8,
  paddingVertical: 10,
  alignItems: "center",
},
sidebarGhostText: {
  color: "#ff8f8f",
  fontWeight: "700",
},
sidebarDangerBtn: {
  borderWidth: 1,
  borderColor: "#b10000",
  borderRadius: 8,
  paddingVertical: 10,
  alignItems: "center",
},
sidebarDangerText: {
  color: "#ff6d6d",
  fontWeight: "700",
},
avatarCircle: {
  width: 110,
  height: 110,
  borderRadius: 55,
  borderWidth: 3,
  borderColor: "#2e313d",
  alignItems: "center",
  justifyContent: "center",
  backgroundColor: "#1c1f29",
},
avatarInitial: {
  color: "#ffffff",
  fontSize: 34,
  fontWeight: "700",
},
infoDivider: {
  height: 1,
  backgroundColor: "#2a2d38",
  alignSelf: "stretch",
  marginVertical: 14,
},
});